version: "3.7"

services:
  chrome:
    image: selenium/standalone-chrome
    container_name: chrome
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4441:4444" # Map Selenium server port
      - "7901:7900" # Map noVNC server port

  firefox:
    image: selenium/standalone-firefox
    container_name: firefox
    hostname: firefox
    privileged: true
    shm_size: 2g
    ports:
      - "4442:4444" # Map Selenium server port
      - "7902:7900" # Map noVNC server port

  edge:
    image: selenium/standalone-edge
    container_name: edge
    hostname: edge
    privileged: true
    shm_size: 2g
    ports:
      - "4443:4444" # Map Selenium server port
      - "7903:7900" # Map noVNC server port
