	name: Maven Selenium TestNG CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main	  	  
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        # Checkout the repository
        - name: Checkout code
          uses: actions/checkout@v3

        # Set up JDK 21
        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '21'

        # Install Docker
        - name: Install Docker
          run: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo apt-get install -y docker-compose
            sudo systemctl start docker
            sudo systemctl enable docker

        # Ensure Docker is installed
        - name: Verify Docker installation
          run: docker --version

        - name: Verify Docker Compose installation
          run: docker-compose --version

        # Run Docker Compose
        - name: Run Docker Compose
          run: docker-compose -f docker-compose-standalone.yml up -d

        # Verify running containers
        - name: List running containers
          run: docker ps

        # Run Maven build
        - name: Run Maven clean install
          run: mvn clean install

        # Tear down Docker Compose
        - name: Tear Down Docker Compose
          run: docker-compose -f docker-compose-standalone.yml down