name: Maven Selenium TestNG CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main	  	  
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        # Checkout the repository
        - name: Checkout code
          uses: actions/checkout@v3

        # Set up Java environment
        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '21'

        # Cache Maven dependencies
        - name: Cache Maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

        # Run Maven build
        - name: Run Maven clean install
          run: mvn clean install